# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "/opt/ml/models")
v <- vetiver_pin_read(b, "credit_best", version = "20230510T200945Z-bbe11")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
